# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/mediaViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from timelineController import *
from videoWidget import *
import threading



class MediaViewer(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__()
        self.parent = parent
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoGroup = VideoWidget(self)
        self.videoGroup.setObjectName("videoGroup")
        self.verticalLayout.addWidget(self.videoGroup, stretch=10)
        self.timelineController = TimelineController(self)
        self.timelineController.setObjectName("timelineController")
        self.timelineController.setMinimumHeight(50)
        self.verticalLayout.addWidget(self.timelineController, stretch=1)
        self.audioGroup = QtWidgets.QWidget(self)
        self.audioGroup.setObjectName("audioGroup")
        self.verticalLayout.addWidget(self.audioGroup, stretch=4)


        self.timelineController.timelineSlider.valueChanged.connect(lambda x: self.videoGroup.setPosition(x))
        self.timelineController.timelineSlider.sliderMoved.connect(lambda x: self.videoGroup.setPosition(x))


def main():
    app = QtWidgets.QApplication([])
    widget = MediaViewer()

    widget.show()
    widget.videoGroup.player.play()
    widget.videoGroup.player.pause()

    app.exec_()

if __name__ == '__main__':
    main()
