# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/timelineController.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TimelineController(QtWidgets.QWidget):
    def __init__(self, parent=None, duration=30526):
        super().__init__()
        self.parent = parent
        self.minimumHeight = 50
        self.timelineControlGrid = QtWidgets.QGridLayout(self)
        self.timelineControlGrid.setContentsMargins(0, 0, 0, 0)
        self.timelineControlGrid.setObjectName("verticalLayout")

        self.toStart = QtWidgets.QPushButton(self)
        self.toStart.setText("\u23EE")
        self.fastBackward = QtWidgets.QPushButton(self)
        self.fastBackward.setText("\u23EA")
        self.playPause = QtWidgets.QPushButton(self)
        self.playPause.setText("\u23EF")
        self.fastForward = QtWidgets.QPushButton(self)
        self.fastForward.setText("\u23E9")
        self.toEnd = QtWidgets.QPushButton(self)
        self.toEnd.setText("\u23ED")

        self.timelineSlider = QtWidgets.QSlider(self)
        self.timelineSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)

        self.timelineControlGrid.addWidget(self.toStart, 0, 0)
        self.timelineControlGrid.addWidget(self.fastBackward, 0, 1)
        self.timelineControlGrid.addWidget(self.playPause, 0, 2)
        self.timelineControlGrid.addWidget(self.fastForward, 0, 3)
        self.timelineControlGrid.addWidget(self.toEnd, 0, 4)
        self.timelineControlGrid.addWidget(self.timelineSlider, 1, 0, 1, 5)



def main():
    app = QtWidgets.QApplication([])
    widget = TimelineController()
    widget.show()
    app.exec_()

if __name__ == '__main__':
    main()
