# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/timelineController.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TimelineController(QtWidgets.QWidget):
    def __init__(self, parent=None, show_coding_buttons=False, duration=30526):
        super().__init__(parent)
        self.minimumHeight = 100
        self.timelineControlGrid = QtWidgets.QGridLayout(self)
        self.timelineControlGrid.setContentsMargins(0, 0, 0, 0)
        self.timelineControlGrid.setObjectName("verticalLayout")

        self.toStart = QtWidgets.QPushButton("\u23EE", self)
        self.fastBackward = QtWidgets.QPushButton("\u23EA", self)
        self.playPause = QtWidgets.QPushButton("\u23EF", self)
        self.fastForward = QtWidgets.QPushButton("\u23E9", self)
        self.toEnd = QtWidgets.QPushButton("\u23ED", self)

        self.timelineSlider = QtWidgets.QSlider(self)
        self.timelineSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)

        if show_coding_buttons:
            self.button_add_code = QtWidgets.QPushButton("Add Datapoint", self)
            self.button_show_data = QtWidgets.QPushButton("Show Datapoints", self)
            self.button_show_data.setCheckable(True)

            self.button_add_code.clicked.connect(lambda state: self.parentWidget().parentWidget().show_code_widget())
            self.button_show_data.toggled.connect(lambda state: self.show_codes())

            self.timelineControlGrid.addWidget(self.button_add_code, 0, 0, 1, 2)
            self.timelineControlGrid.addWidget(self.button_show_data, 0, 3, 1, 2)
            self.timelineControlGrid.addWidget(self.toStart, 1, 0)
            self.timelineControlGrid.addWidget(self.fastBackward, 1, 1)
            self.timelineControlGrid.addWidget(self.playPause, 1, 2)
            self.timelineControlGrid.addWidget(self.fastForward, 1, 3)
            self.timelineControlGrid.addWidget(self.toEnd, 1, 4)
            self.timelineControlGrid.addWidget(self.timelineSlider, 2, 0, 1, 5)
        else:
            self.timelineControlGrid.addWidget(self.toStart, 0, 0)
            self.timelineControlGrid.addWidget(self.fastBackward, 0, 1)
            self.timelineControlGrid.addWidget(self.playPause, 0, 2)
            self.timelineControlGrid.addWidget(self.fastForward, 0, 3)
            self.timelineControlGrid.addWidget(self.toEnd, 0, 4)
            self.timelineControlGrid.addWidget(self.timelineSlider, 1, 0, 1, 5)

    def show_codes(self):
        print("Do something")



def main():
    app = QtWidgets.QApplication([])
    widget = TimelineController()
    widget.show()
    app.exec_()

if __name__ == '__main__':
    main()
