# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/timelineController.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TimelineController(QtWidgets.QWidget):
    def __init__(self, parent=None, duration=30526):
        super().__init__()
        self.parent = parent
        self.duration = duration
        self.minimumHeight = 50
        self.timelineSlider = QtWidgets.QSlider(self)
        self.timelineSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.timelineSlider.setMaximum(self.duration)
        self.timelineSlider.adjustSize()



    def resizeEvent(self, a0: QtGui.QResizeEvent):
        self.timelineSlider.resize(self.width(), self.height())


def main():
    app = QtWidgets.QApplication([])
    widget = TimelineController()
    widget.show()
    app.exec_()

if __name__ == '__main__':
    main()
